### ISSUE TITLE
Too many requests?

### ISSUE THREAD

**Issue by PatchwerkQWER** [Netifriik/node-steam-market-manager#1]
Hi,

I have little problem. I make request every 15s and after ~300 items i get "We are making too many requests to Steam.".

My question is: how big delay i should have to break ban checker?

Thanks :)

**Comment by pepzwee** [comment]
I'm not entirely sure what the Steam request limit is. When I was testing my requests were 12.5 seconds apart without hitting the "Too Many Requests" error.

Now I just use a proxy network so that I don't have to worry about that.

**Comment by PatchwerkQWER** [comment]
Can you tell me, which proxy network you use? Thanks for your request

**Comment by pepzwee** [comment]
http://rev.proxies.online
